// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Y6KPS23gXkzIvMIUooLHziO7558rnPw',
    appId: '1:178956682333:web:be0c4c38a52880e8b139b4',
    messagingSenderId: '178956682333',
    projectId: 'articulation-149bd',
    authDomain: 'articulation-149bd.firebaseapp.com',
    storageBucket: 'articulation-149bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdOUT52tDpHTyglNU-S2I2pGMFAzjtwI0',
    appId: '1:178956682333:android:0012a9d8f13f004fb139b4',
    messagingSenderId: '178956682333',
    projectId: 'articulation-149bd',
    storageBucket: 'articulation-149bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC85y4k5ATmbNdele5CCVs6blffoB7leXk',
    appId: '1:178956682333:ios:59d8078a90edab5cb139b4',
    messagingSenderId: '178956682333',
    projectId: 'articulation-149bd',
    storageBucket: 'articulation-149bd.firebasestorage.app',
    iosBundleId: 'com.KISR.articulationV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC85y4k5ATmbNdele5CCVs6blffoB7leXk',
    appId: '1:178956682333:ios:5bfaac1d1b2f1aeab139b4',
    messagingSenderId: '178956682333',
    projectId: 'articulation-149bd',
    storageBucket: 'articulation-149bd.firebasestorage.app',
    iosBundleId: 'com.example.articulation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Y6KPS23gXkzIvMIUooLHziO7558rnPw',
    appId: '1:178956682333:web:cebc8a32c752d90cb139b4',
    messagingSenderId: '178956682333',
    projectId: 'articulation-149bd',
    authDomain: 'articulation-149bd.firebaseapp.com',
    storageBucket: 'articulation-149bd.firebasestorage.app',
  );
}
